import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";
import { LinearGradient } from "expo-linear-gradient";
import API from "../services/api";
import ScreenWrapper from "../components/ScreenWrapper";
const money = (amount?: number) => `₹ ${Number(amount || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
export default function PayslipsScreen() {
  const [payslips, setPayslips] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = async () => { try { const response = await API.get("/payroll/payslips/me"); setPayslips(response.data); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { load(); }, []);
  if (loading) return <ScreenWrapper><View style={styles.loader}><ActivityIndicator size="large" color="#2F80ED" /></View></ScreenWrapper>;
  return <ScreenWrapper><ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} />}><LinearGradient colors={["#0F2027", "#203A43", "#2C5364"]} style={styles.header}><Text style={styles.title}>My Payslips</Text><Text style={styles.subtitle}>Your monthly salary statements</Text></LinearGradient>{payslips.length === 0 ? <Text style={styles.empty}>No payslips have been published yet.</Text> : payslips.map((slip) => <View style={styles.card} key={slip.id}><View style={styles.row}><Text style={styles.month}>{slip.payrollMonth}</Text><Text style={styles.net}>{money(slip.netSalary)}</Text></View><Text style={styles.caption}>Net salary</Text><View style={styles.divider} /><Line label="Basic salary" value={slip.basicSalary} /><Line label="Allowances" value={slip.totalAllowances} /><Line label="Gross salary" value={slip.grossSalary} /><Line label="PF" value={slip.providentFund} negative /><Line label="Professional tax" value={slip.professionalTax} negative /><Line label="Income tax" value={slip.incomeTax} negative /><Line label="Other deductions" value={slip.otherDeductions} negative /><Line label={`Absence deduction (${slip.unpaidDays} day(s))`} value={slip.absenceDeduction} negative /><Line label="Total deductions" value={slip.totalDeductions} negative bold /></View>)}</ScrollView></ScreenWrapper>;
}
function Line({ label, value, negative, bold }: { label: string; value: number; negative?: boolean; bold?: boolean }) { return <View style={styles.line}><Text style={bold ? styles.bold : styles.caption}>{label}</Text><Text style={[bold ? styles.bold : styles.value, negative && styles.negative]}>{negative ? "− " : ""}{money(value)}</Text></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#F4F6FB" }, content: { padding: 20, paddingBottom: 40 }, loader: { flex: 1, alignItems: "center", justifyContent: "center" }, header: { padding: 24, borderRadius: 20, marginBottom: 20 }, title: { color: "#fff", fontWeight: "bold", fontSize: 30 }, subtitle: { color: "rgba(255,255,255,0.72)", marginTop: 6 }, card: { backgroundColor: "#fff", borderRadius: 18, padding: 18, marginBottom: 14, elevation: 2 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline" }, month: { fontSize: 19, fontWeight: "700" }, net: { color: "#16A085", fontSize: 20, fontWeight: "bold" }, caption: { color: "#64748B", fontSize: 13, marginTop: 4 }, divider: { height: 1, backgroundColor: "#E2E8F0", marginVertical: 13 }, line: { flexDirection: "row", justifyContent: "space-between", marginBottom: 9 }, value: { fontSize: 13, color: "#1E293B" }, negative: { color: "#DC2626" }, bold: { fontSize: 13, fontWeight: "700", color: "#1E293B" }, empty: { textAlign: "center", color: "#64748B", marginTop: 50 } });
